site_title = "WangRongsheng Arxiv"
limit_days = 7
cache_url = "https://wangrongsheng.github.io/wrsArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
